/* Allegro datafile object indexes, produced by dat v4.0.3, MSVC */
/* Datafile: c:\work\mapper\mapper.dat */
/* Date: Thu Dec 29 21:18:48 2005 */
/* Do not hand edit! */

#define BABY_MET_F01                     0        /* BMP  */
#define BABY_MET_F02                     1        /* BMP  */
#define BABY_MET_F03                     2        /* BMP  */
#define BG01                             3        /* BMP  */
#define BG02                             4        /* BMP  */
#define BG03                             5        /* BMP  */
#define BG04                             6        /* BMP  */
#define BG05                             7        /* BMP  */
#define BG06                             8        /* BMP  */
#define BLK_F01                          9        /* BMP  */
#define BLK_F02                          10       /* BMP  */
#define BLK_FLL_F01                      11       /* BMP  */
#define BLK_FLL_F02                      12       /* BMP  */
#define BLK_FLL_F03                      13       /* BMP  */
#define BLK_FLL_F04                      14       /* BMP  */
#define BLT_GN2_F01                      15       /* BMP  */
#define BLT_GN2_F02                      16       /* BMP  */
#define BLT_GN2_F03                      17       /* BMP  */
#define BLT_GN3_F01                      18       /* BMP  */
#define BLT_GN3_F02                      19       /* BMP  */
#define BLT_GN3_F03                      20       /* BMP  */
#define BLT_NME_F01                      21       /* BMP  */
#define BLT_NRM_F01                      22       /* BMP  */
#define BLT_PURPLE_F01                   23       /* BMP  */
#define BLT_PURPLE_F02                   24       /* BMP  */
#define BLT_SMS_F01                      25       /* BMP  */
#define BLT_SMS_F02                      26       /* BMP  */
#define BLT_SMS_F03                      27       /* BMP  */
#define BMB_BLK_F01                      28       /* BMP  */
#define BMB_EXP_F01                      29       /* BMP  */
#define BMB_EXP_F02                      30       /* BMP  */
#define BMB_EXP_F03                      31       /* BMP  */
#define BMB_EXP_F04                      32       /* BMP  */
#define BMB_EXP_F05                      33       /* BMP  */
#define BMP_DBALL_F01                    34       /* BMP  */
#define BMP_DBALL_F02                    35       /* BMP  */
#define BOMB_BRICK                       36       /* BMP  */
#define BOMB_F01                         37       /* BMP  */
#define BOMB_F02                         38       /* BMP  */
#define DOOR_F01                         39       /* BMP  */
#define DOOR_F02                         40       /* BMP  */
#define DOOR_F03                         41       /* BMP  */
#define DOOR_F04                         42       /* BMP  */
#define DOOR_F05                         43       /* BMP  */
#define DOOR_F06                         44       /* BMP  */
#define DSH_F01                          45       /* BMP  */
#define DSH_F02                          46       /* BMP  */
#define DSH_F03                          47       /* BMP  */
#define DSH_F04                          48       /* BMP  */
#define DSH_F05                          49       /* BMP  */
#define ENEMY01_F01                      50       /* BMP  */
#define ENEMY_ARC                        51       /* BMP  */
#define ENEMY_THREEWAY                   52       /* BMP  */
#define EXP_F01                          53       /* BMP  */
#define EXP_F02                          54       /* BMP  */
#define EXP_F03                          55       /* BMP  */
#define EXP_F04                          56       /* BMP  */
#define EXP_F05                          57       /* BMP  */
#define EXP_F06                          58       /* BMP  */
#define EXP_F07                          59       /* BMP  */
#define EXP_F08                          60       /* BMP  */
#define FAKE_WALL1                       61       /* BMP  */
#define FLR_BLK_F01                      62       /* BMP  */
#define FLR_BLK_F02                      63       /* BMP  */
#define FRT_WLK_F01                      64       /* BMP  */
#define FRT_WLK_F02                      65       /* BMP  */
#define FRT_WLK_F03                      66       /* BMP  */
#define FRT_WLK_F04                      67       /* BMP  */
#define FRT_WLK_F05                      68       /* BMP  */
#define FRT_WLK_F06                      69       /* BMP  */
#define FRT_WLK_F07                      70       /* BMP  */
#define FRT_WLK_F08                      71       /* BMP  */
#define FRT_WLK_F09                      72       /* BMP  */
#define FRT_WLK_F10                      73       /* BMP  */
#define FRT_WLK_F11                      74       /* BMP  */
#define GAME_FONT                        75       /* FONT */
#define GOOGLE_F01                       76       /* BMP  */
#define GOOGLE_F02                       77       /* BMP  */
#define GUITAR_PROTO                     78       /* SAMP */
#define HEART_F01                        79       /* BMP  */
#define HEART_F02                        80       /* BMP  */
#define HEART_F03                        81       /* BMP  */
#define HEART_F04                        82       /* BMP  */
#define ICON_NINJA                       83       /* BMP  */
#define ITEM01_F01                       84       /* BMP  */
#define ITEM02_F01                       85       /* BMP  */
#define ITEM_PLASMA                      86       /* BMP  */
#define LEV_CUR_F01                      87       /* BMP  */
#define LEV_CUR_F02                      88       /* BMP  */
#define LEV_SEL_BG                       89       /* BMP  */
#define LEV_SEL_FG                       90       /* BMP  */
#define LIFE_BAR                         91       /* BMP  */
#define LIFE_BAR_BASE                    92       /* BMP  */
#define LIFE_BAR_EMPTY                   93       /* BMP  */
#define LIFE_BAR_TOP                     94       /* BMP  */
#define LOGO                             95       /* BMP  */
#define MAIN_MENU                        96       /* BMP  */
#define MAP01                            97       /* MAP  */
#define MAP02                            98       /* MAP  */
#define MAP03                            99       /* MAP  */
#define MAP04                            100      /* MAP  */
#define MAP05_FALLSPIKE                  101      /* MAP  */
#define MAP999_LAST                      102      /* MAP  */
#define MAP_ICON_MET                     103      /* BMP  */
#define MAP_ICON_MET_DIM                 104      /* BMP  */
#define MAP_ICON_X                       105      /* BMP  */
#define MAP_ICON_X_DIM                   106      /* BMP  */
#define MEGAMAN1_BIG                     107      /* BMP  */
#define MEGAMANX_BIG                     108      /* BMP  */
#define MEGAMANX_ICON                    109      /* BMP  */
#define MET_CAN_F01                      110      /* BMP  */
#define MET_CAN_F02                      111      /* BMP  */
#define MET_CAN_F03                      112      /* BMP  */
#define MET_CAN_F04                      113      /* BMP  */
#define METCAPSULE                       114      /* BMP  */
#define MIDI_NICESHOT                    115      /* MIDI */
#define MM1_BULLET_F01                   116      /* BMP  */
#define MM1_SLIDE                        117      /* BMP  */
#define MM1_STD_F01                      118      /* BMP  */
#define MM1_WLK_F01                      119      /* BMP  */
#define MM1_WLK_F02                      120      /* BMP  */
#define MM1_WLK_F03                      121      /* BMP  */
#define MM1_WLKF_F00                     122      /* BMP  */
#define MM1_WLKF_F01                     123      /* BMP  */
#define MM1_WLKF_F02                     124      /* BMP  */
#define MM1_WLKF_F03                     125      /* BMP  */
#define MMX_CNG_F01                      126      /* BMP  */
#define MMX_DSH_F01                      127      /* BMP  */
#define MMX_DSH_F02                      128      /* BMP  */
#define MMX_FLL_F01                      129      /* BMP  */
#define MMX_HIT_F01                      130      /* BMP  */
#define MMX_HIT_F02                      131      /* BMP  */
#define MMX_JMP_F01                      132      /* BMP  */
#define MMX_JMP_F02                      133      /* BMP  */
#define MMX_JMP_F03                      134      /* BMP  */
#define MMX_JMP_F04                      135      /* BMP  */
#define MMX_JMP_SHT_F01                  136      /* BMP  */
#define MMX_JMP_SHT_F02                  137      /* BMP  */
#define MMX_JMP_SHT_F03                  138      /* BMP  */
#define MMX_JMP_SHT_F04                  139      /* BMP  */
#define MMX_STD_F01                      140      /* BMP  */
#define MMX_STD_SHT_F01                  141      /* BMP  */
#define MMX_TELE_F01                     142      /* BMP  */
#define MMX_TELE_F02                     143      /* BMP  */
#define MMX_TELE_F03                     144      /* BMP  */
#define MMX_TELE_F04                     145      /* BMP  */
#define MMX_TELE_F05                     146      /* BMP  */
#define MMX_TELE_F06                     147      /* BMP  */
#define MMX_TELE_F07                     148      /* BMP  */
#define MMX_WLK_F01                      149      /* BMP  */
#define MMX_WLK_F02                      150      /* BMP  */
#define MMX_WLK_F03                      151      /* BMP  */
#define MMX_WLK_F04                      152      /* BMP  */
#define MMX_WLK_F05                      153      /* BMP  */
#define MMX_WLK_F06                      154      /* BMP  */
#define MMX_WLK_F07                      155      /* BMP  */
#define MMX_WLK_F08                      156      /* BMP  */
#define MMX_WLK_F09                      157      /* BMP  */
#define MMX_WLK_F10                      158      /* BMP  */
#define MMX_WLK_F11                      159      /* BMP  */
#define MMX_WLK_SHT_F01                  160      /* BMP  */
#define MMX_WLK_SHT_F02                  161      /* BMP  */
#define MMX_WLK_SHT_F03                  162      /* BMP  */
#define MMX_WLK_SHT_F04                  163      /* BMP  */
#define MMX_WLK_SHT_F05                  164      /* BMP  */
#define MMX_WLK_SHT_F06                  165      /* BMP  */
#define MMX_WLK_SHT_F07                  166      /* BMP  */
#define MMX_WLK_SHT_F08                  167      /* BMP  */
#define MMX_WLK_SHT_F09                  168      /* BMP  */
#define MMX_WLK_SHT_F10                  169      /* BMP  */
#define MMX_WLK_SHT_F11                  170      /* BMP  */
#define MUSIC01                          171      /* MIDI */
#define MUSIC02                          172      /* MIDI */
#define MUSIC03                          173      /* MIDI */
#define MUSIC04                          174      /* MIDI */
#define MUSIC05                          175      /* MIDI */
#define MUSIC06                          176      /* MIDI */
#define MUSIC07                          177      /* MIDI */
#define MUSIC08                          178      /* MIDI */
#define MUSIC09                          179      /* MIDI */
#define MUSIC10                          180      /* MIDI */
#define MUSIC11                          181      /* MIDI */
#define MUSIC12                          182      /* MIDI */
#define MUSIC13                          183      /* MIDI */
#define MUSIC14                          184      /* MIDI */
#define MUSIC15                          185      /* MIDI */
#define NINJA_CNG_F01                    186      /* BMP  */
#define NINJA_DSH_F01                    187      /* BMP  */
#define NINJA_DSH_F02                    188      /* BMP  */
#define NINJA_FLL_F01                    189      /* BMP  */
#define NINJA_HIT_F01                    190      /* BMP  */
#define NINJA_HIT_F02                    191      /* BMP  */
#define NINJA_JMP_F01                    192      /* BMP  */
#define NINJA_JMP_F02                    193      /* BMP  */
#define NINJA_JMP_F03                    194      /* BMP  */
#define NINJA_JMP_F04                    195      /* BMP  */
#define NINJA_JMP_SHT_F01                196      /* BMP  */
#define NINJA_JMP_SHT_F02                197      /* BMP  */
#define NINJA_JMP_SHT_F03                198      /* BMP  */
#define NINJA_JMP_SHT_F04                199      /* BMP  */
#define NINJA_STD_F01                    200      /* BMP  */
#define NINJA_STD_SHT_F01                201      /* BMP  */
#define NINJA_TELE_F01                   202      /* BMP  */
#define NINJA_TELE_F02                   203      /* BMP  */
#define NINJA_TELE_F03                   204      /* BMP  */
#define NINJA_TELE_F04                   205      /* BMP  */
#define NINJA_TELE_F05                   206      /* BMP  */
#define NINJA_TELE_F06                   207      /* BMP  */
#define NINJA_TELE_F07                   208      /* BMP  */
#define NINJA_WLK_F01                    209      /* BMP  */
#define NINJA_WLK_F02                    210      /* BMP  */
#define NINJA_WLK_F03                    211      /* BMP  */
#define NINJA_WLK_F04                    212      /* BMP  */
#define NINJA_WLK_F05                    213      /* BMP  */
#define NINJA_WLK_F06                    214      /* BMP  */
#define NINJA_WLK_F07                    215      /* BMP  */
#define NINJA_WLK_F08                    216      /* BMP  */
#define NINJA_WLK_F09                    217      /* BMP  */
#define NINJA_WLK_F10                    218      /* BMP  */
#define NINJA_WLK_F11                    219      /* BMP  */
#define NINJA_WLK_SHT_F01                220      /* BMP  */
#define NINJA_WLK_SHT_F02                221      /* BMP  */
#define NINJA_WLK_SHT_F03                222      /* BMP  */
#define NINJA_WLK_SHT_F04                223      /* BMP  */
#define NINJA_WLK_SHT_F05                224      /* BMP  */
#define NINJA_WLK_SHT_F06                225      /* BMP  */
#define NINJA_WLK_SHT_F07                226      /* BMP  */
#define NINJA_WLK_SHT_F08                227      /* BMP  */
#define NINJA_WLK_SHT_F09                228      /* BMP  */
#define NINJA_WLK_SHT_F10                229      /* BMP  */
#define NINJA_WLK_SHT_F11                230      /* BMP  */
#define NINJASTAR_F01                    231      /* BMP  */
#define NINJASTAR_F02                    232      /* BMP  */
#define PAUSE_MENU                       233      /* BMP  */
#define POSE_MEGAMAN1                    234      /* BMP  */
#define POSE_PROTO                       235      /* BMP  */
#define POSE_SAMUS                       236      /* BMP  */
#define POSE_SHADOWMAN                   237      /* BMP  */
#define PUFF_F01                         238      /* BMP  */
#define PUFF_F02                         239      /* BMP  */
#define PUFF_F03                         240      /* BMP  */
#define PUFF_F04                         241      /* BMP  */
#define PUFF_F05                         242      /* BMP  */
#define PUFF_F06                         243      /* BMP  */
#define SAMP_BADSEL                      244      /* SAMP */
#define SAMP_CHOOSE                      245      /* SAMP */
#define SAMP_CHRG                        246      /* SAMP */
#define SAMP_DASH                        247      /* SAMP */
#define SAMP_DEATH                       248      /* SAMP */
#define SAMP_GUN1                        249      /* SAMP */
#define SAMP_GUN2                        250      /* SAMP */
#define SAMP_HEART                       251      /* SAMP */
#define SAMP_JUMP                        252      /* SAMP */
#define SAMP_LAND                        253      /* SAMP */
#define SAMP_LIFEGIVE                    254      /* SAMP */
#define SAMP_METITEM                     255      /* SAMP */
#define SAMP_MM1_JUMP                    256      /* SAMP */
#define SAMP_MM1_SHOOT                   257      /* SAMP */
#define SAMP_MMX_HIT                     258      /* SAMP */
#define SAMP_NINJA_VANISH                259      /* SAMP */
#define SAMP_NME_DIE                     260      /* SAMP */
#define SAMP_NME_HIT                     261      /* SAMP */
#define SAMP_SEL                         262      /* SAMP */
#define SAMP_SMS_BOMB                    263      /* SAMP */
#define SAMP_SMS_HIT                     264      /* SAMP */
#define SAMP_SMS_SHOT                    265      /* SAMP */
#define SAMP_SMS_WLK                     266      /* SAMP */
#define SAMP_TALKSOUND                   267      /* SAMP */
#define SAMP_TELE_IN                     268      /* SAMP */
#define SAMUS_BOMB_F01                   269      /* BMP  */
#define SAMUS_BOMB_F02                   270      /* BMP  */
#define SAMUS_BOMB_F03                   271      /* BMP  */
#define SCRIPT01                         272      /* MMS  */
#define SCRIPT02_METITEM                 273      /* MMS  */
#define SCRIPT03_TEST                    274      /* MMS  */
#define SCRIPT04_MM1_DEFEAT              275      /* MMS  */
#define SCRIPT05_SHADOW_DEFEAT           276      /* MMS  */
#define SCRIPT06_MET_WARNING             277      /* MMS  */
#define SCRIPT07_SHADOW_SCRIPT           278      /* MMS  */
#define SCRIPT08_SECRET_WELCOME          279      /* MMS  */
#define SCRIPT09_SECRET_BEAT             280      /* MMS  */
#define SCRIPT999_LAST                   281      /* MMS  */
#define SCRIPT_TESTINGDAT                282      /* MMS  */
#define SCROLL_TILE                      283      /* BMP  */
#define SIGMAS                           284      /* BMP  */
#define SMS_BLL_F01                      285      /* BMP  */
#define SMS_BLL_F02                      286      /* BMP  */
#define SMS_BLL_F03                      287      /* BMP  */
#define SMS_BLL_F04                      288      /* BMP  */
#define SMS_BLL_F05                      289      /* BMP  */
#define SMS_BLL_F06                      290      /* BMP  */
#define SMS_BLL_F07                      291      /* BMP  */
#define SMS_BLL_F08                      292      /* BMP  */
#define SMS_BLL_F09                      293      /* BMP  */
#define SMS_BLL_F10                      294      /* BMP  */
#define SMS_CNG_F01                      295      /* BMP  */
#define SMS_DCK_F01                      296      /* BMP  */
#define SMS_JMP_F01                      297      /* BMP  */
#define SMS_JMP_F02                      298      /* BMP  */
#define SMS_JMP_F03                      299      /* BMP  */
#define SMS_JMP_F04                      300      /* BMP  */
#define SMS_JMP_F05                      301      /* BMP  */
#define SMS_STD_F01                      302      /* BMP  */
#define SMS_WLK_F01                      303      /* BMP  */
#define SMS_WLK_F02                      304      /* BMP  */
#define SMS_WLK_F03                      305      /* BMP  */
#define SMS_WLK_F04                      306      /* BMP  */
#define SMS_WLK_F05                      307      /* BMP  */
#define SMS_WLK_F06                      308      /* BMP  */
#define SMS_WLK_F07                      309      /* BMP  */
#define SMS_WLK_F08                      310      /* BMP  */
#define SMS_WLK_F09                      311      /* BMP  */
#define SMS_WLK_F10                      312      /* BMP  */
#define SPIKER_F01                       313      /* BMP  */
#define SPIKER_F02                       314      /* BMP  */
#define SPIKER_F03                       315      /* BMP  */
#define STAR_F01                         316      /* BMP  */
#define STAR_F02                         317      /* BMP  */
#define STAR_F03                         318      /* BMP  */
#define STAR_F04                         319      /* BMP  */
#define STARTX_TILE                      320      /* BMP  */
#define STARTY_TILE                      321      /* BMP  */
#define TILE_SHEET1                      322      /* BMP  */
#define TILE_SHEET2                      323      /* BMP  */
#define TILE_SHEET3                      324      /* BMP  */
#define TILE_SHEET999_LAST               325      /* BMP  */
#define TILE_TYPES1                      326      /* TTYP */
#define TILE_TYPES2                      327      /* TTYP */
#define TILE_TYPES3                      328      /* TTYP */
#define TILE_TYPES999_LAST               329      /* TTYP */
#define WHEEL_F01                        330      /* BMP  */
#define WHEEL_F02                        331      /* BMP  */
#define WHEEL_F03                        332      /* BMP  */
#define WHEEL_F04                        333      /* BMP  */
#define ZERO_BIG                         334      /* BMP  */

